apiVersion: apps/v1
kind: Deployment
metadata:
  name: rdyhtrh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rdyhtrh
  template:
    metadata:
      labels:
        app: rdyhtrh
    spec:
      containers:
      - image: okteto.dev/rdyhtrh:latest
        name: rdyhtrh
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "063d8fe2-af9b-44d3-879e-2902f67be996"
        - name: Vless_Path
          value: "/jkdytjtdsh897"
        - name: Vmess_UUID
          value: "063d8fe2-af9b-44d3-879e-2902f67be996"
        - name: Vmess_Path
          value: "/uihstrhyhe345"
        - name: Share_Path
          value: "/v2link"
